### ISSUE TITLE
Fossils And Portals

### ISSUE THREAD

**Issue by SliMHaZe** [superlord9362/Prehistoric-Fauna#26]
So I Was Very Excited To Use This Mod But I Was Having Some Major Issues, So When I Tried To Make A Museum With The Fossils I Realized That The Skeletons Where Mobs And They Kept Turing And Ruining The Posing That I Tried To Put Them In. Than After I Gave Up On The Fossils I Went To Use The Portals And Found Out That The Portals Didn't Even Work SO Plz Fix This Issue... But Other Than That The Mod Is Great! Its Just Sad That There's Still Some Major issues Like This...

**Comment by superlord9362** [comment]
What do you mean with the turning issue? Did they just continuously turn, or was it an issue with relogging? As for portals, they've been proving to be an inconsistent issue, with many people having issues varying between locations in a world, and just between worlds themselves. With Skeletons, there isn't much we can do about them turning on relogging, as there's no way to save the direction they're looking at occasionally. As for portals, they'll hopefully be much more fixed in the 1.16 version that will be started soon.

**Comment by superlord9362** [comment]
Closed due to lack of information and 1.16 port.
